 
<!-- Path way -->
<ul class="pathway">
    <li><a href="#">Home</a></li>
    <li class="sep"><img src="<?php echo $this->baseUrl('img/spacer.gif'); ?>" alt="" /></li>
    <li><a href="#">Blog</a></li>
    <li class="sep"><img src="<?php echo $this->baseUrl('img/spacer.gif'); ?>" alt="" /></li>
    <li>Blog With Right Sidebar</li>
</ul>
<!-- /Path way-->    
<!-- LeftCol -->
<div class="cont_leftcol">
    <!-- BlogList -->
    <div class="greyblock">
        <div class="cont">
            <img src="<?php echo $this->baseUrl('img/pic_blog3-1.jpg'); ?>" alt="" class="pic_left" />
            <span class="blog_type">PS2</span>
            <h4 class="blog_head">Age   Of   Empires</h4>
            <p><span class="blog_date">Posted on Saturday, April 30 th, 2011 at 12:33 pm by <a href="#">admin</a></span>                  Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu lacus. Vestibulum libero nisl, porta vel, scelerisque eget, malesuada at, neque. Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse sollicitudin velit sed leo. Ut pharetra augue nec augue. Nam elit agna,endrerit sit amet, tincidunt ac, viverra sed, nulla. Donec porta diam eu massa. Quisque diam lorem, interdum vitae,dapibus ac, scelerisque vitae, pede. Donec eget tellus non erat lacinia fermentum.</p>
            <p> Donec in velit vel ipsum auctor pulvinar. Vestibulum iaculis lacinia est. Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet, consectetuer adipis. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor. </p>
        </div>
        <div class="sep"></div>
        <div class="pad bottom_spacing15">
            <div class="fleft">
                <ul class="left_social">
                    <li><img src="<?php echo $this->baseUrl('img/ico_facelike.jpg'); ?>" alt="" width="50" height="24" /></li>
                    <li><img src="<?php echo $this->baseUrl('img/ico_googleplus.jpg'); ?>" alt="" width="65" height="24" /></li>
                </ul>
            </div>
            <div class="fright">
                <ul class="right_social">
                    <li>Share this:</li>
                    <li><a href="#"><img src="<?php echo $this->baseUrl('img/ico_ltl_f.jpg'); ?>" alt="" /></a></li>
                    <li><a href="#"><img src="<?php echo $this->baseUrl('img/ico_ltl_t.jpg'); ?>" alt="" /></a></li>
                    <li><a href="#"><img src="<?php echo $this->baseUrl('img/ico_ltl_2x2.jpg'); ?>" alt="" /></a></li>
                    <li><a href="#"><img src="<?php echo $this->baseUrl('img/ico_ltl_circ.jpg'); ?>" alt="" /></a></li>
                    <li><a href="#"><img src="<?php echo $this->baseUrl('img/ico_ltl_mail.jpg'); ?>" alt="" /></a></li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div class="cont">
            <img src="<?php echo $this->baseUrl('img/pic_noava_big.jpg'); ?>" alt="" class="pic_left" />
            <h4>About the author: <a href="#">admin</a></h4>
            Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse sollicitudin velit sed leo.
            <div class="clear"></div>
        </div>
    </div>       
    <!-- Comments Block -->
    <div class="greyblock">
        <h4 class="ttl">3 Comments</h4>
        <ul class="blog_comments_list">
            <li><div class="cont"><img src="<?php echo $this->baseUrl('img/pic_noava.jpg') ?>" alt="" />
                    <h4><a href="#">Adam Smith</a> says</h4>
                    <span class="date">2011-02-10 12:55:39</span><br />
                    Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis
                    in faucibus orci luctus et ultrices posuere.
                    <a href="#" class="reply">Reply</a>
                </div>
                <ul>
                    <li><div class="cont"><img src="<?php echo $this->baseUrl('img/pic_noava.jpg'); ?>" alt="" />
                            <h4><a href="#">Admin</a> says</h4>
                            <span class="date">2011-02-10 12:55:39</span><br />                                
                            ESuspendisse sollicitudin velit sed leo.
                            <a href="#" class="reply">Reply</a>
                        </div></li>
                </ul>
            </li>
            <li><div class="cont"><img src="<?php echo $this->baseUrl('img/pic_noava.jpg'); ?>" alt="" />
                    <h4><a href="#">Cindy Johnson</a> says</h4>
                    <span class="date">2011-02-10 12:55:39</span><br />
                    Nam elit agna,endrerit sit amet, tincidunt ac, viverra sed, nulla. Donec porta diam eu massa.
                    <a href="#" class="reply">Reply</a>
                </div></li>
        </ul>
    </div>
    <!-- Leave Comment -->
    <div class="greyblock">
        <div class="pad">
            <h4>Leave a Comment</h4>
            <p>Your email address will not be published. Required fields are marked *</p>
            <form id="form1" name="form1" method="post" action="#" class="comment_form">
                <label class="comform_name">
                    Name<span class="red">*</span>
                    <input type="text" name="textfield2" id="textfield2" class="inp" />
                </label>
                <label class="comform_email">
                    Email<span class="red">*</span>
                    <input type="text" name="textfield3" id="textfield3" class="inp" />
                </label>
                <div class="clear"></div>
                <label>
                    Subject<br />
                    <input type="text" name="textfield4" id="textfield4" class="inp1" />
                </label>
                <div class="clear"></div>
                <label>
                    Message<span class="red">*</span><br />
                    <textarea name="textarea" id="textarea" cols="45" rows="5" class="area"></textarea>
                </label><br />
                <input type="submit" name="button2" id="button2" value="" class="btn_post" />
            </form>                    
        </div>
    </div>
</div>
<!-- /LeftCol -->
<!-- RightCol -->
<div class="cont_rightcol">
    <div class="gradientblock">
        <!-- Popular Post -->
        <h4>Popular Posts</h4>
        <ul class="popular_posts">
            <li>
                <img src="<?php echo $this->baseUrl('img/pic_news1.jpg'); ?>" alt="" />
                <span>Donec sagittis euismod purus</span>
                Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu acus.
                <br class="clear" />
            </li>
            <li>
                <img src="<?php echo $this->baseUrl('img/pic_news2.jpg'); ?>" alt="" />
                <span>Nam elit agna, endrerit sit</span>
                Vestibulum libero nisl, porta vel, scelerisque eget, malesuada at, neque.
                <br class="clear" />
            </li>
            <li>
                <img src="<?php echo $this->baseUrl('img/pic_news3.jpg'); ?>" alt="" />
                <span>Sed in lacus ut enim adipiscing</span>
                Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere.
                <br class="clear" />
            </li>
        </ul>
    </div>
    <!-- /Popular Post -->   	    	
    <!-- Recent Comments -->
    <div class="greyblock">
        <h4 class="ttl">Recent Comments</h4>
        <ul class="rec_comments_list">
            <li><img src="<?php echo $this->baseUrl('img/pic_noava.jpg'); ?>" alt="" />
                <a href="#">Adam Smith</a><br />
                <span class="date">2011-02-10 12:55:39</span><br />
                <span class="posted">Posted a comment on:</span>
                <br class="clear" />
                Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis
                in faucibus orci luctus et ultrices posuere.</li>
            <li><img src="<?php echo $this->baseUrl('img/pic_noava.jpg'); ?>" alt="" />
                <a href="#">Admin</a><br />
                <span class="date">2011-02-10 12:55:39</span><br />
                <span class="posted">Posted a comment on:</span>
                <br class="clear" />
                ESuspendisse sollicitudin velit sed leo.</li>
            <li><img src="<?php echo $this->baseUrl('img/pic_noava.jpg'); ?>" alt="" />
                <a href="#">Cindy Johnson</a><br />
                <span class="date">2011-02-10 12:55:39</span><br />
                <span class="posted">Posted a comment on:</span>
                <br class="clear" />
                Nam elit agna,endrerit sit amet, tincidunt ac, viverra sed, nulla. Donec porta diam eu massa. </li>					
        </ul>
    </div>
    <!-- /Recent Comments -->
    <!-- New Block -->
    <div class="greenblock">            	
        <div class="new_logo"></div>
        <h4><a href="http://vimeo.com/10736308">PlayStation 3 Move Trailer: GDC 2010</a></h4>
        <div class="cont">
            <iframe src="http://player.vimeo.com/video/10736308?title=0&amp;byline=0&amp;portrait=0" width="285" height="158" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>
    </div>
    <!-- /New Block -->
</div>
<!-- /RightCol -->
<div class="clear"></div>
