
<!-- TopGallery -->
<div class="d-gallery">
    <img src="img/toppic1.jpg" alt="" id="topgal1" class="toppic"/>
    <img src="<?php echo $this->linkTo('index', 'image', NULL, array('file' => urlencode('img/toppic2.jpg'), 'w' => 960, 'h' => 440)); ?>" alt="" id="topgal2" class="toppic"/>
    <img src="<?php echo $this->linkTo('index', 'image', NULL, array('file' => urlencode('img/toppic3.jpg'), 'w' => 960, 'h' => 440)); ?>" alt="" id="topgal3" class="toppic"/>
    <div id="topgal_fadder"></div>
    <ul>
        <li id="toppic1">
            <img src="img/toppic1_thmb.jpg" alt="" />
            xbox 360<br />
            <span>Midnight Club 3</span>
            <a href="#">Read more</a>
        </li>
        <li id="toppic2">
            <img src="<?php echo $this->linkTo('index', 'image', NULL, array('file' => urlencode('img/toppic2_thmb.jpg'), 'w' => 120, 'h' => 80)); ?>" alt="" />
            PC<br />
            <span>sniper elite 3</span>
            <a href="#">Read more</a>
        </li>
        <li id="toppic3">
            <img src="<?php echo $this->linkTo('index', 'image', NULL, array('file' => urlencode('img/toppic3_thmb.jpg'), 'w' => 120, 'h' => 80)); ?>" alt="" />
            PS4<br />
            <span>watch_dogs</span>
            <a href="#">Read more</a>
        </li>
    </ul>
</div>
<!--/Gallery -->

<!-- New Articles Block -->
<div class="greyblock">
    <div id="gal_block1">
        <div class="tabblock1">
            <ul>
                <li class="latest act">Latest</li>
                <li class="top_rated">Top Rated</li>
                <li class="most_popular">Most Popular</li>
            </ul>
            <a href="javascript:void(0)" class="btn_left" rel="slider1"></a>
            <a href="javascript:void(0)" class="btn_right" rel="slider1"></a>                
        </div>
        <div class="slidegallery" id="slidegallery1">
            <div id="latest" class="slidegal_categ">
                <ul class="slider1 vis" id="first">
                    <li>
                        <img src="img/pic_article1.jpg" alt="" />
                        <span>PC</span>
                        <h4>Need   For   Speed</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article2.jpg" alt="" />
                        <span>PS2</span>
                        <h4>runescape</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article3.jpg" alt="" />
                        <span>Mobile</span>
                        <h4>Stalker</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article4.jpg" alt="" />
                        <span>3DS</span>
                        <h4>age   of   empires</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article1.jpg" alt="" />
                        <span>PC</span>
                        <h4>Need   For   Speed</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article2.jpg" alt="" />
                        <span>PS2</span>
                        <h4>runescape</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article3.jpg" alt="" />
                        <span>Mobile</span>
                        <h4>Stalker</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article4.jpg" alt="" />
                        <span>3DS</span>
                        <h4>age   of   empires</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                </ul>
            </div>
            <div id="top_rated" class="slidegal_categ">
                <ul class="slider1">
                    <li>
                        <img src="img/pic_article1.jpg" alt="" />
                        <span>PC</span>
                        <h4>Need   For   Speed</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article2.jpg" alt="" />
                        <span>PS2</span>
                        <h4>runescape</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article3.jpg" alt="" />
                        <span>Mobile</span>
                        <h4>Stalker</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article4.jpg" alt="" />
                        <span>3DS</span>
                        <h4>age   of   empires</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article1.jpg" alt="" />
                        <span>PC</span>
                        <h4>Need   For   Speed</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article2.jpg" alt="" />
                        <span>PS2</span>
                        <h4>runescape</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article3.jpg" alt="" />
                        <span>Mobile</span>
                        <h4>Stalker</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article4.jpg" alt="" />
                        <span>3DS</span>
                        <h4>age   of   empires</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                </ul>
            </div>
            <div id="most_popular" class="slidegal_categ">
                <ul class="slider1">
                    <li>
                        <img src="img/pic_article1.jpg" alt="" />
                        <span>PC</span>
                        <h4>Need   For   Speed</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article2.jpg" alt="" />
                        <span>PS2</span>
                        <h4>runescape</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article3.jpg" alt="" />
                        <span>Mobile</span>
                        <h4>Stalker</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article4.jpg" alt="" />
                        <span>3DS</span>
                        <h4>age   of   empires</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article1.jpg" alt="" />
                        <span>PC</span>
                        <h4>Need   For   Speed</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article2.jpg" alt="" />
                        <span>PS2</span>
                        <h4>runescape</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article3.jpg" alt="" />
                        <span>Mobile</span>
                        <h4>Stalker</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                    <li>
                        <img src="img/pic_article4.jpg" alt="" />
                        <span>3DS</span>
                        <h4>age   of   empires</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>							</li>
                </ul>
            </div>                
        </div>
    </div>
</div>
<!-- /New Articles Block -->

<!-- LeftCol -->
<div class="cont_leftcol">
    <!-- TopGames -->
    <div class="greyblock">
        <div class="tabblock1">
            <ul>
                <li class="act">Top Games</li>
            </ul>
            <a href="javascript:void(0)" class="btn_left" rel="slider2"></a>
            <a href="javascript:void(0)" class="btn_right" rel="slider2"></a>                
        </div>
        <div class="slidegallery" id="slidegallery2">
            <div class="slidegal_categ">
                <ul class="slider2 vis">
                    <li>
                        <img src="img/pic_topgames1.jpg" alt="" />
                        <span>PC</span>
                        <h4>Line   Age   II</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>
                    </li>
                    <li>
                        <img src="img/pic_topgames2.jpg" alt="" />
                        <span>PS2</span>
                        <h4>Civcity   Rome</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>
                    </li>
                    <li>
                        <img src="img/pic_topgames3.jpg" alt="" />
                        <span>Mobile</span>
                        <h4>Burnout   Revenge</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>
                    </li>   
                    <li>
                        <img src="img/pic_topgames1.jpg" alt="" />
                        <span>PC</span>
                        <h4>Line   Age   II</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>
                    </li>
                    <li>
                        <img src="img/pic_topgames2.jpg" alt="" />
                        <span>PS2</span>
                        <h4>Civcity   Rome</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>
                    </li>
                    <li>
                        <img src="img/pic_topgames3.jpg" alt="" />
                        <span>Mobile</span>
                        <h4>Burnout   Revenge</h4>
                        Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Donec sit amet eros. 
                        <a href="#" class="read">Read more</a>
                    </li>                        	
                </ul>
            </div>					
        </div>
    </div>
    <!-- /TopGames -->    
    <!-- GameBox View -->
    <?php echo $this->gameBoxWidget(); ?>
    <!-- /GameBox View -->
    <!-- Breaking News -->
    <?php echo $this->newsWidget(); ?>
    <!-- /Breaking News -->
</div>
<!-- /LeftCol -->

<!-- RightCol -->
<div class="cont_rightcol">
    <!-- New Block -->
    <div class="greenblock">            	
        <div class="new_logo"></div>
        <h4><a href="http://vimeo.com/10736308">PlayStation 3 Move Trailer: GDC 2010</a></h4>
        <div class="cont">
            <iframe src="http://player.vimeo.com/video/10736308?title=0&amp;byline=0&amp;portrait=0" width="285" height="158" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>
    </div>
    <!-- /New Block -->
    <!-- Recent Comments -->
    <div class="greyblock">
        <h4 class="ttl">Recent Comments</h4>
        <ul class="rec_comments_list">
            <li>
                <img src="img/pic_noava.jpg" alt="" />
                <a href="#">Adam Smith</a><br />
                <span class="date">2011-02-10 12:55:39</span><br />
                <span class="posted">Posted a comment on:</span>
                <br class="clear" />
                Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere.
            </li>
            <li>
                <img src="img/pic_noava.jpg" alt="" />
                <a href="#">Admin</a><br />
                <span class="date">2011-02-10 12:55:39</span><br />
                <span class="posted">Posted a comment on:</span>
                <br class="clear" />
                ESuspendisse sollicitudin velit sed leo.
            </li>
            <li>
                <img src="img/pic_noava.jpg" alt="" />
                <a href="#">Cindy Johnson</a><br />
                <span class="date">2011-02-10 12:55:39</span><br />
                <span class="posted">Posted a comment on:</span>
                <br class="clear" />
                Nam elit agna,endrerit sit amet, tincidunt ac, viverra sed, nulla. Donec porta diam eu massa. 
            </li>
            <li>
                <img src="img/pic_noava.jpg" alt="" />
                <a href="#">Patrick Pool</a><br />
                <span class="date">2011-02-10 12:55:39</span><br />
                <span class="posted">Posted a comment on:</span>
                <br class="clear" />
                Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet, consectetuer adipis.
            </li>
        </ul>
    </div>
    <!-- /Recent Comments -->
</div>
<!-- /RightCol -->
<div class="clear"></div>


